apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sourcebot-secrets
stringData:
  postgresql-password: password
  redis-password: password
  authSecret: "CHANGEME" # generate via `openssl rand -base64 33`
  encryptionKey: "CHANGEME" # generate via `openssl rand -base64 24`
