---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sourcebot.fullname" $ }}
  labels:
    {{- include "sourcebot.labels" $ | nindent 4 }}
data:
  config.json:  |
    {{- toJson $.Values.sourcebot.config | nindent 4 }}
