---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sourcebot.fullname" $ }}
  labels:
    {{- include "sourcebot.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.sourcebot.service.type }}
  ports:
    - port: {{ $.Values.sourcebot.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- range $.Values.sourcebot.additionalPorts }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "sourcebot.selectorLabels" $ | nindent 4 }}
