---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sourcebot.fullname" $ }}
  labels:
    {{- include "sourcebot.labels" $ | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sourcebot.selectorLabels" $ | nindent 4 }}
