apiVersion: v2
type: application
name: sourcebot
version: 0.1.3
appVersion: v4.8.1
description: Sourcebot is a self-hosted tool that helps you understand your codebase.
icon: https://raw.githubusercontent.com/sourcebot-dev/sourcebot/ebf6721836b8f878d42bb8c1e844bdc7867a74fe/packages/web/public/logo_512.png
keywords:
  - code-search
  - code-intelligence
  - sourcebot
home: https://sourcebot.dev/
sources:
  - https://github.com/sourcebot-dev/sourcebot
  - https://github.com/sourcebot-dev/sourcebot/kubernetes/chart
dependencies:
  - name: postgresql
    version: 16.4.9
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.deploy
  - name: valkey
    version: 2.2.4
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.deploy
    alias: redis