name: Validate Helm Chart
on:
  pull_request:
    paths:
      - 'charts/**'
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Install helm-docs
        run: |
          cd /tmp
          curl -L https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.tar.gz | tar xz
          sudo mv helm-docs /usr/local/bin/

      - name: Update dependencies
        run: helm dependency update charts/sourcebot/

      - name: Run helm lint
        run: helm lint charts/sourcebot/ -f charts/sourcebot/values.lint.yaml

      - name: Validate helm-docs
        run: |
          helm-docs charts/sourcebot/
          if [[ $(git diff --stat) != '' ]]; then
            echo 'Chart documentation is out of date. Please run helm-docs and commit the changes.'
            echo 'Git diff:'
            git diff
            exit 1
          fi

